<?php
$items = $this->getProducts();
?>
<?php if ($items):?>

    <div class="block-title title">
        <strong id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></strong>
    </div>
    <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">
        <div class="products wrapper grid products-grid products-<?php /* @escapeNotVerified */ echo $type; ?>">
            <?php $iterator = 0; ?>
            <?php foreach ($items as $_item):
                $iterator++;
                switch ($iterator)  {
                    case 1:
                        $class = 'green';
                        break;
                    case 2:
                        $class = 'yellow';
                        break;
                    case 3:
                        $class = 'orange';
                        break;
                }
                ?>
                <div class="product product-<?php /* @escapeNotVerified */ echo $type; ?> <?php echo $class?>">
                    <?php
                    $specialprice = $_item->getSpecialPrice();
                    $price = $_item->getPrice();
                    ?>
                    <div class="ribbon ribbon-top-right">
                        <?php   if ($specialprice) :?>
                            <span>£<?php echo round($price-$specialprice); ?><?php echo __(' Discount'); ?></span>
                        <?php endif; ?>
                    </div>
                    <div class="col-xs-12 col-md-8">
                        <div class="inner">
                            <div class="product-title">
                                <span><?php echo __($_item->getName()); ?></span>
                                <div class="subtitle">
                                    <?php if($level = $_item->getLevel()) : ?>
                                        <span class="level"><?php echo __('Level '.$level); ?></span>
                                    <?php endif; ?>
                                    <?php if($unitCount = $_item->getUnitCount()) : ?>
                                        <span class="level"><?php echo __($unitCount.' Units'); ?></span>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <div class="content">
                                <?php
                                $factory  = \Magento\Framework\App\ObjectManager::getInstance();
                                $page = $factory->get('FishPig\WordPress\Model\Post')->load($_item->load($_item->getId())->getData('associated_page'));?>
                                <?php
                                echo  $post->getExcerpt();
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-4">
                        <div class="inner">
                            <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
                            <div class="actions">
                                <?php

                                ?>
                                <a class="action tocart primary btn-blue-standard"
                                   href="<?php echo $_item->getProductUrl(); ?>"
                                   title="<?php /* @escapeNotVerified */ echo __('View') ?>">
                                    <span><?php /* @escapeNotVerified */ echo __('View') ?></span>
                                </a>
                                <form data-role="tocart-form" action="<?php echo $this->getAddToCartUrl($_item); ?>" method="post" class="add-to-cart-related">
                                    <?php echo $block->getBlockHtml('formkey')?>
                                    <button class="action tocart primary btn-blue-standard"
                                            data-post='<?php /* @escapeNotVerified */ echo $block->getPostData($_item); ?>'
                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart1') ?>">
                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach ?>
        </div>
    </div>
<?php endif;?>
