<?php $_product = $block->getProduct();
$post = $block->getPost();
$buttonTitle = __("Add to Basket");
?>
<?php if($_product->getFinalPrice() > 0) : ?>
<div class="siderbar-cart">
    <div class="openText"><?php echo __('Ready To Buy?'); ?><span
            class="glyphicon glyphicon-chevron-up pull-right"></span></div>

    <?php echo $block->getChildHtml('product.info.sidebar'); ?>
</div>
<?php endif; ?>
