<?php $_product = $block->getProduct();
$post = $block->getPost();
$buttonTitle = __("Add to Basket");
$type = $_product->getData('type_id');
?>

<div class="siderbar-cart">
    <div class="openText"><?php echo __('Ready To Buy?'); ?><span
            class="glyphicon glyphicon-chevron-up pull-right"></span></div>

    <?php echo $block->getChildHtml('product.info.sidebar'); ?>

    <?php
    if ($_product->isSaleable()): ?>
        <div class="box-tocart">
            <div class="inner">
                <div class="fieldset">

                    <?php if ($_product->isSaleable()): ?>
                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post"  class="add-to-cart-related">
                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo 'uenc'; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
                            <?php echo $block->getBlockHtml('formkey')?>


                            <?php if ($block->shouldRenderQuantity()): ?>
                                <div class="field qty">
                                    <label class="label" for="qty"><span><?php /* @escapeNotVerified */
                                            echo __('Qty') ?></span></label>
                                    <div class="control">
                                        <input type="number"
                                               name="qty"
                                               id="qty"
                                               maxlength="12"
                                               value="<?php /* @escapeNotVerified */
                                               echo $block->getProductDefaultQty() * 1 ?>"
                                               title="<?php /* @escapeNotVerified */
                                               echo __('Qty') ?>" class="input-text qty"
                                               data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                                        />
                                    </div>
                                </div>
                            <?php endif; ?>
                            <div class="actions">
                                <button type="submit"
                                        title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                        class="action primary tocart <?php echo ($type == 'bundle') ?'bundle-addtocart' : 'simple-addtocart'; ?>">
                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                </button>
                            </div>
                        </form>
                    <?php else: ?>
                        <?php if ($_product->getIsSalable()): ?>
                            <div class="stock available add-to-cart-related"><span class="primary btn-blue-standard"><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                        <?php else: ?>
                            <div class="stock unavailable add-to-cart-related"><span class="primary btn-blue-standard"><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
                <?php if($post->getMetaValue('application_form')) : ?>
                    <div class="application">
                        <p><span class="underline-text">

                        <a href="<?php echo $post->getMetaValue('application_form'); ?>"
                           download="<?php echo $post->getPostName(); ?>">
                            Download Application Form
                        </a>
                    </span>
                        </p>
                    </div>
                <?php endif; ?>
            </div>
            <div class="cart-footer">
                <a class="single-units btn-blue-standard" href="#">Single Units From £120</a>
            </div>
        </div>
    <?php endif; ?>
</div>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>

<?php if($type == 'bundle'): ?>
<script>// <![CDATA[
    require([
        'jquery',
        'bootstrap/modal'
    ], function ($,ajaxproduct) {

        var getUrlParameter = function getUrlParameter(sParam) {
            var sPageURL = decodeURIComponent(window.location.search.substring(1)),
                sURLVariables = sPageURL.split('&'),
                sParameterName,
                i;

            for (i = 0; i < sURLVariables.length; i++) {
                sParameterName = sURLVariables[i].split('=');

                if (sParameterName[0] === sParam) {
                    return sParameterName[1] === undefined ? true : sParameterName[1];
                }
            }
        };

        if( getUrlParameter('options') == 'cart')
        {
            $('.bundle-addtocart').trigger('click');
        }

        $('.bundle-addtocart').on('click', function(e) {
            $('#addtocartmodal').bsmodal('show');
            e.preventDefault();
        });

    });
    // ]]>
</script>
<?php endif ?>