<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct();
$post = $block->getPost();
$buttonTitle = __("Add to Basket");
?>
<?php if ($_product->isSaleable() && $_product->getFinalPrice() > 0): ?>
    <div class="box-tocart">
        <div class="inner">
            <div class="fieldset">
                <?php if ($block->shouldRenderQuantity()): ?>
                    <div class="field qty">
                        <label class="label" for="qty"><span><?php /* @escapeNotVerified */
                                echo __('Qty') ?></span></label>
                        <div class="control">
                            <input type="number"
                                   name="qty"
                                   id="qty"
                                   maxlength="12"
                                   value="<?php /* @escapeNotVerified */
                                   echo $block->getProductDefaultQty() * 1 ?>"
                                   title="<?php /* @escapeNotVerified */
                                   echo __('Qty') ?>" class="input-text qty"
                                   data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                            />
                        </div>
                    </div>
                <?php endif; ?>
                <div class="actions" data-product-id="<?php echo $_product->getId();?>" >
                    <button type="submit"
                            title="<?php /* @escapeNotVerified */
                            echo $buttonTitle ?>"
                            class="action primary tocart <?php echo ($_product->getTypeId() === 'simple' && !filter_var($_product->getData('has_options'), FILTER_VALIDATE_BOOLEAN)) ? 'simple-addtocart' : ''; ?>"
                            id="product-addtocart-button">
                        <span><?php /* @escapeNotVerified */
                            echo $buttonTitle ?></span>
                    </button>
                    <?php echo $block->getChildHtml('', true) ?>
                </div>
            </div>
            <?php if($post->getMetaValue('application_form')) : ?>
                <div class="application">
                    <p><span class="underline-text">

                        <a href="<?php echo $post->getMetaValue('product_application_upload'); ?>"
                           download="<?php echo $post->getPostName(); ?>">
                          <?php /* @escapeNotVerified */ echo __('Download Application Form'); ?>
                        </a>
                    </span>
                    </p>
                </div>
            <?php endif; ?>
        </div>
        <?php if($_product->getTypeId() === 'bundle'): ?>
            <div class="cart-footer">
                <a class="single-units btn-blue-standard" href="<?php echo $lowestUrl; ?>"><?php /* @escapeNotVerified */ echo __('Single units from £'.($lowest*1.2)); ?></a>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }



</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": true
            }
        }
    }



    </script>
<?php endif; ?>
