<div class="modal fade" id="addtocartmodal" tabindex="-1" role="dialog" aria-hidden="true"  aria-labelledby="addtocartmodal">
    <div class="modal-dialog modal-lg" role="document">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <div class="modal-content">

            <div class="modal-body page-main">

                <div class="columns two-columns2">
                    <div class="column main">
                        <div class="page-title-wrapper product">
                            <h2>Configure Your Course</h2>
                        </div>
                        <div class="wp-content">
                            <?php echo $block->getChildHtml('product.info.simples',true); ?>
                            <?php echo $block->getChildHtml('product.info.addons',true); ?>
                        </div>
                    </div>
                    <div class="sidebar sidebar-main">
                        <?php echo $block->getChildHtml('product_form_sidebar'); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="termsModal" class="modal fade modal-child" data-backdrop-limit="1" tabindex="-1" role="dialog" aria-labelledby="termsModal" aria-hidden="true" data-modal-parent="#addtocartmodal">
    <div class="modal-dialog">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <div class="modal-content">
            <div class="modal-body">
                <div class="modal-inner-shadow">
                    <h3><?php echo __('Terms &amp; Conditions'); ?></h3>
                    <div class="content">
                        <?php echo $block->getChildHtml('product.info.terms',true); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>// <![CDATA[
    require([
        'jquery',
        'bootstrapjs-datepicker'
    ], function ($) {
        $('.modal-child').on('show.bs.modal', function () {
            var modalParent = $(this).attr('data-modal-parent');
            $(modalParent).css('opacity', 0);
        });

        $('.modal-child').on('hidden.bs.modal', function () {
            var modalParent = $(this).attr('data-modal-parent');
            $(modalParent).css('opacity', 1);
            if ($('body').hasClass('modal-open') == false) {
                $('body').addClass('modal-open');
            };
        });



        $('.induction .yes-no-wrapper a').on('click',function(event){
            if($(this).hasClass('active') == false)
            {
                $('.induction .yes-no-wrapper a').removeClass('active');
                $(this).addClass('active');
                if($(this).text() == 'Yes')
                {
                    $('#datetimepicker12').datetimepicker({
                        inline: true,
                        sideBySide: true,
                        format: "dd MM yyyy"
                    });

                    $("#datetimepicker12").on("dp.change", function(e) {
                        console.log(e.date);
                        select = $( "legend span:contains('Introduction Date')" ).parent().find('select');
                        console.log(select);
                    });

                }else{
                    $('#datetimepicker12').data("DateTimePicker").destroy();
                }
            }
            event.preventDefault();
        });

    });
    // ]]>
</script>