<div class="modal fade" id="addtocartmodal" tabindex="-1" role="dialog" aria-labelledby="addtocartmodal">
    <div class="modal-dialog modal-lg" role="document">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <div class="modal-content">

            <div class="modal-body page-main">

                <div class="columns two-columns2">
                    <div class="column main">
                        <div class="page-title-wrapper product">
                            <h2>Configure Your Course</h2>
                        </div>
                        <div class="wp-content">
                            <?php echo $block->getChildHtml('product.info.simples',true); ?>
                            <?php echo $block->getChildHtml('product.info.addons',true); ?>
                        </div>
                    </div>
                    <div class="sidebar sidebar-main">
                        <?php echo $block->getChildHtml('product.info.modal',true); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>