<?php
    $post = $this->getPost();
    $product = $this->getProduct();
    $contentBefore =  $post->getMetaValue('product_blocks_before_units');
    $contentAfter  =  $post->getMetaValue('product_blocks_after_units');


    echo $post->clean($post->getMainContent());


    if($contentBefore != null) {
        foreach ($contentBefore as $row) {
            foreach ($row as $field) {
                if ($field instanceof WP_Post) {
                    $newPost = $this->getPostById($field->ID);
                    echo $post->clean($newPost->getMainContent());
                }
            }
        }
    }
    if($product->getTypeId() == 'bundle') {
        echo $block->getChildHtml('product.info.bundles');
    }

    if($contentAfter != null) {
        foreach ($contentAfter as $row) {
            foreach ($row as $field) {
                if ($field instanceof WP_Post) {
                    $newPost = $this->getPostById($field->ID);
                    echo $post->clean($newPost->getMainContent());
                }
            }
        }
    }
?>

