<?php
$post = $this->getPost();
$contentBefore = $post->getMetaValue('product_blocks_before_units');
$contentAfter = $post->getMetaValue('product_blocks_after_units');
$product = $this->getProduct();

?>
<a data-toggle="collapse" href="#productScroll" class=" visible-xs jumpto">Jump To<i class="fa fa-chevron-down"></i></a>
<nav id="productScroll" class="panel-collapse collapse in">

        <div class="panel-body">
    <ul class="nav nav-pills nav-stacked">
        <li><a href="#introduction" class="circle"><span>Introduction</span></a></li>
        <?php
        if ($contentBefore != null) {
            foreach ($contentBefore as $row) {
                foreach ($row as $field) {
                    if ($field instanceof WP_Post) {
                        $id = preg_replace("/[^-[:^punct:]]/", "",strtolower(str_replace(" ","-",$field->post_title)));
                        ?>
                        <li><a href="#<?php echo $id; ?>" class="circle"><span><?php echo $field->post_title; ?></span></a>
                        </li>
                        <?php
                    }
                }
            }
        }
        ?>
        <?php if($product->getTypeId() == 'bundle') : ?>
            <li><a href="#units" class="circle"><span>Units</a></span></li>
        <?php endif; ?>
        <?php

        if ($contentAfter != null) {
            foreach ($contentAfter as $row) {
                foreach ($row as $field) {
                    if ($field instanceof WP_Post) {
                        $id = preg_replace("/[^-[:^punct:]]/", "",strtolower(str_replace(" ","-",$field->post_title)));
                        ?>
                        <li><a href="#<?php echo $id; ?>" class="circle"><span><?php echo $field->post_title; ?></span></a>
                        </li>
                        <?php
                    }
                }
            }
        }
        ?>
        <?php
        $collectoon = $this->getProduct()->getRelatedProductCollection()->addAttributeToSelect(
            'required_options'
        )->setPositionOrder()->addStoreFilter()->setVisibility([2,4]);
        $collectoon->addMinimalPrice()
           ->addFinalPrice()
           ->addTaxPercents()
           ->addUrlRewrite();
        foreach ($collectoon as $product) {
            $product->setDoNotUseCategoryId(true);
        }
        if($collectoon->count() >0) : ?>
            <li><a href="#related" class="circle"><span>Related</span></a></li>
        <?php endif; ?>
    </ul>
            </div>
</nav>
<script>// <![CDATA[
    require([
        'jquery',
        'scrollnav',
        'domReady!'
    ], function ($,scrollNav) {
            $(document).ready(function(){
                var win = $(window); //this = window

                $.fn.resized = function (callback, timeout) {
                    $(this).resize(function () {
                        var $this = $(this);
                        if ($this.data('resizeTimeout')) {
                            clearTimeout($this.data('resizeTimeout'));
                        }
                        $this.data('resizeTimeout', setTimeout(callback, timeout));
                    });
                };

                function resize() {
                    if (win.width() >= 768) {
                        scrollNav._init();
                    } else {
                        $('#maincontent .siderbar-cart').off('.affix');
                        $('#maincontent #productScroll').off('.affix');
                    }
                }

                $(window).resized(resize, 300);

            })
    });
    // ]]>
</script>
