<div class="modal fade termsModalSimple" data-backdrop-limit="1" tabindex="-1" role="dialog" aria-labelledby="termsModal" aria-hidden="true">
    <div class="modal-dialog">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <div class="modal-content">
            <div class="modal-body">
                <div class="modal-inner-shadow">
                    <h3 class="text text-center"><?php echo __('Terms &amp; Conditions'); ?></h3>
                    <div class="content">
                        <div class="text text-center">
                            <div class="terms">
                                <?php
                                if($_product = $this->getProduct()):
	                                if($_product->getTypeId() != 'bundle') :
		                                $contentBefore =  $wpPages->getMetaValue('product_blocks_before_units');
		                                $contentAfter  =  $wpPages->getMetaValue('product_blocks_after_units');

		                                $terms = "";

		                                if($contentBefore != null) {
			                                foreach ($contentBefore as $row) {
				                                foreach ($row as $field) {
					                                if ($field instanceof WP_Post) {
						                                $newPost = $this->getPostById($field->ID);
						                                if(stripos(strtolower($newPost->getPostTitle()), 'terms and conditions') !== false) {
							                                $terms .= $newPost->getMainContent();
						                                }
					                                }
				                                }
			                                }
		                                }

		                                if($contentAfter != null) {
			                                foreach ($contentAfter as $row) {
				                                foreach ($row as $field) {
					                                $newPost = $this->getPostById($field->ID);
					                                if(stripos(strtolower($newPost->getPostTitle()), 'terms and conditions') !== false) {
						                                $terms .= $newPost->getMainContent();
					                                }
				                                }
			                                }
		                                }

		                                echo $post->clean($terms);
	                                endif;
                                endif;
                                ?>
                            </div>
                            <div class="subtitle error terms-agreed">
                                <span><i class="fa fa-exclamation-triangle" aria-hidden="true"></i><?php echo __("These must be accepted by the user."); ?></span>
                            </div>
                            <a href="" class="btn-green-solid agree"><span><?php echo __('Agree and Add to Basket'); ?></span></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>// <![CDATA[
    require([
        'jquery',
        'domReady!'
    ], function ($) {

        agreed = false;
        currentId = 0;
        currentAddToCart = null;
        $('.simple-addtocart').on('click', function(event)
        {
            console.log(currentAddToCart);
            console.log($(this));
            if(currentAddToCart !== null) {
                if (!currentAddToCart.is($(this))) {
                    agreed = false;
                    currentAddToCart = $(this);
                    currentId = $(this).parent().attr('data-product-id');
                }
            }else {
                currentAddToCart = $(this);
            }

            if(agreed === false) {
                terms = $(this).closest('.inner').find('.hidden-terms').html();
                $('.termsModalSimple .terms').html(terms);
                $('.termsModalSimple').bsmodal('show');
                event.preventDefault();
            }

        });

        $('.termsModalSimple .agree').on('click',function(event){
            agreed=true;
            console.log(currentAddToCart);
            currentAddToCart.trigger('click');
            event.preventDefault();
        });

    });
    // ]]>
</script>
