<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
$_product = $block->getProduct();
?>
<?php if ($_product->isSaleable() && $block->hasOptions()): ?>
	<div id="simleSummary"
	     class="block-simple-summary">
		<div class="title">
			<strong><?php /* @escapeNotVerified */ echo __('Your Customization'); ?></strong>
		</div>
		<div class="content">
			<div class="simple-info">
				<div class="product-details">
					<strong class="product name"><?php echo $block->escapeHtml($_product->getName()) ?></strong>
					<?php if ($_product->getIsSalable()): ?>
						<p class="available stock" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
							<span><?php /* @escapeNotVerified */ echo __('In stock') ?></span>
						</p>
					<?php else: ?>
						<p class="unavailable stock" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
							<span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span>
						</p>
					<?php endif; ?>
					<?php echo $block->getChildHtml('', true);?>
				</div>
			</div>
		</div>
	</div>
<?php endif; ?>
