<div id="units" class="wrapper-block simple-products">
    <?php foreach ($this->getOptions() as $option):
        if ($option->getTitle() != 'Induction day') :
            ?>
            <div class="one-column">
                <div class="column">
                    <h3 class="title"><?php echo $option->getTitle(); ?><span
                            class="subtitle"><?php echo __('Units essential to this qualification'); ?></span></h3>
                    <table class="table bundle-simples">
                        <?php
                        foreach ($option->getSelections() as $data) :
                            $data->load($data->getId()); ?>
                            <tr>
                                <td>
                                    <?php echo $data->getSku(); ?>
                                </td>
                                <td>
                                    <?php echo $data->getName(); ?>
                                </td>
                                <td>

                                </td>
                                <td>
                                    <a class="btn-blue-standard open-simple" data-id="<?php echo $data->getId(); ?>">
                                        <?php echo __('View Unit'); ?>
                                    </a>
                                </td>
                            </tr>
                            <tr class="separator"/>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
            <?php
        endif;
    endforeach; ?>
</div>



