<?php
$_item = $this->getProduct();
$_post = $this->getPostById($_item->getData('associated_page'));
$count = 1;
?>
<!--
<div class="grey">
    <div class="add-to-cart-title">
        <div class="circle-with-text small pull-left">
            2
        </div>
        <div class="text pull-left">
            <h3 class="title"><span>Add-ons</span><span
                    class="subtitle">Please Select any optional add-ons you require</span></h3>
        </div>
    </div>
    <div class="products wrapper grid products-related">
        <div class="product product-related green">
            <div class="col-xs-12 col-md-8">
                <div class="inner">
                    <div class="product-title">
                        <span><?php echo __($_item->getName()); ?></span>
                        <span class="subtitle error">
                            <span><i class="fa fa-exclamation-triangle" aria-hidden="true"></i><?php echo __("If you have already had an induction you don't need to book another one."); ?></span>
                        </span>
                    </div>
                    <div class="content">

                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-md-4">
                <div class="inner">
                    <div class="product-info-price">
                        <div class="price-box price-final_price" data-role="priceBox">

<span class="price-container price-final_price tax weee">
        <span id="product-price-<?php echo $_item->getId(); ?>"
              data-price-amount="12.50" data-price-type="" class="price-wrapper ">
        <span class="price">£12.50</span>    </span>

        </span>
                            <span class="price-content text-center">
            <span class="vat">Plus VAT</span>
        </span>
                        </div>
                    </div>

                    <div class="inner">

                        <div class="actions">
                            <span class="check on"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
-->
<?php
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customOptions = $_objectManager->get('Magento\Catalog\Model\Product\Option')->getProductOptionCollection($_item);
$induction = false;
$inductionId = false;

$inductionDate = false;
$inductionDateId = false;

$inductionLocationId = false;
$inductionLocation = false;


foreach ($customOptions as $option):

    if (strtolower($option->getTitle()) === strtolower('Induction Day')):
        $induction = true;
        $inductionId =  $option->getId();
    endif;

    if (strtolower($option->getTitle()) === strtolower('Induction Date')):
        $inductionDate = true;
        $inductionDateId =  $option->getId();
    endif;

    if (strtolower($option->getTitle()) === strtolower('Induction Location')):
        $inductionLocation = true;
        $inductionLocationId =  $option->getId();
    endif;
endforeach;
?>
<?php if ($induction) : ?>
    <div class="white induction">
        <div class="add-to-cart-title">
            <div class="circle-with-text small pull-left">
                <span></span>
            </div>
            <div class="text pull-left">
                <h3 class="title"><span><?php echo __('Do you Require an induction?'); ?></span>
                    <span class="subtitle "><?php echo __('Inductions are optional and are an introduction to the CILEx Law School, rather than being course specific.'); ?>
                        <span class="error inline"><i class="fa fa-exclamation-triangle"
                                 aria-hidden="true"></i><?php echo __("Thes are not course specific so please only select one date if you're enrolling on more than one course."); ?></span>

                    </span>

                </h3>
                <div class="content">
                    <div class="yes-no-wrapper" data-options-id="<?php echo $inductionId; ?>">
                        <a href="" data-induction="yes">Yes</a>
                        <a href="" data-induction="no" class="active">No</a>
                    </div>
                    <?php if ($inductionDate): ?>
                        <div class="col-xs-12 col-md-6">
                           <div id="datetimepicker12" data-options-id="<?php echo $inductionDateId; ?>"></div>
                        </div>
                        <?php if($inductionLocation): ?>
                            <div class="col-xs-12 col-md-6">
                        <?php
                        $id = 0;
                        $level3Id = 84;
                        $level6Id = 93;
                        $gtfdId = 96;


                        switch($_item->getAttributeText('induction_type'))
                        {
                            case __('Level 3 induction'):
                                $id = $level3Id;
                                break;
                            case __('Level 6 induction'):
                                $id = $level6Id;
                                break;
                            case __('GTFD induction'):
                                $id = $gtfdId;
                                break;
                        }

                        $collection = $_objectManager->get('FishPig\WordPress\Model\Term')->load($id);
                        $collection = $collection->getPostCollection()->addFieldToFilter('name', array('like' => '%induction%'));

                        foreach($collection as $event) :
                            var_dump($event->getMetaValue('_EventVenueID'))
                            ?>
                            <div class="radio confirm-terms margin">
                                <label>
                                    <?php $location = $_objectManager->get('FishPig\WordPress\Model\Post')->load($event->getMetaValue('_EventVenueID'));?>
                                    <input type="radio" class='induction-date' data-date-options-id="<?php echo $inductionDateId; ?>"
                                           data-location-options-id="<?php echo $inductionLocationId; ?>"
                                           data-location="<?php echo $location->getName(); ?>"
                                           data-date="<?php echo $event->getMetaValue('_EventStartDate');?>" /> <?php echo $event->getName(); ?>
                                </label>
                            </div>
                        <?php endforeach; ?>
                    </div>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>

    </div>
    <?php
endif;
?>
<div class="white">
    <div class="add-to-cart-title">
        <div class="circle-with-text small pull-left">
            <span></span>
        </div>
        <div class="text pull-left">
            <h3 class="title no-padding-bottom "><span class="inline">I have read and understood the</span> <span class="underline-text"><a
                            href="#termsModal" role="button" data-target="#termsModal" data-toggle="modal">terms and conditions </a></span>
                <span class="subtitle block terms-agreed">
                <span class="error "><i class="fa fa-exclamation-triangle"
                         aria-hidden="true"></i><?php echo __("These must be accepted by the user."); ?></span>
                </span>
            </h3>
            <div class="checkbox confirm-terms margin">
                <label>
                    <input type="checkbox" name="confirm-terms" id="confirm-terms" /> Confirm
                </label>
            </div>

        </div>
    </div>
</div>

<div class="add-to-cart arrow" style="opacity:0;">
    <span><?php echo __('Thank you, please proceed to payment.'); ?></span></div>