<?php
$_item = $this->getProduct();
$_post = $this->getPostById($_item->getData('associated_page'));
?>
<div class="grey">
    <div class="add-to-cart-title">
        <div class="circle-with-text small pull-left">
            2
        </div>
        <div class="text pull-left">
            <h3 class="title"><span>Add-ons</span><span
                    class="subtitle">Please Select any optional add-ons you require</span></h3>
        </div>
    </div>
    <div class="products wrapper grid products-related">
        <div class="product product-related green">
            <div class="col-xs-12 col-md-8">
                <div class="inner">
                    <div class="product-title">
                        <span><?php echo __($_item->getName()); ?></span>
                        <span class="subtitle error">
                            <span><i class="fa fa-exclamation-triangle" aria-hidden="true"></i><?php echo __("If you have already had an induction you don't need to book another one."); ?></span>
                        </span>
                    </div>
                    <div class="content">

                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-md-4">
                <div class="inner">
                    <div class="product-info-price">
                        <div class="price-box price-final_price" data-role="priceBox">

<span class="price-container price-final_price tax weee">
        <span id="product-price-<?php echo $_item->getId(); ?>"
              data-price-amount="12.50" data-price-type="" class="price-wrapper ">
        <span class="price">£12.50</span>    </span>

        </span>
                            <span class="price-content text-center">
            <span class="vat">Plus VAT</span>
        </span>
                        </div>
                    </div>

                    <div class="inner">

                        <div class="actions">
                            <span class="check on"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="white">
    <div class="add-to-cart-title">
        <div class="circle-with-text small pull-left">
            3
        </div>
        <div class="text pull-left">
            <h3 class="title"><span>Do you Require an induction?</span>
                <span class="subtitle">Inductions are optional and are an introduction to the CILEx Law School, rather than being course specific.</span>
                <span class="subtitle error">
                    <span><i class="fa fa-exclamation-triangle" aria-hidden="true"></i><?php echo __("Thes are not course specific soplease only selectone date if yoiu are enrolling on more than one course."); ?></span>
                </span>
            </h3>
            <div class="content">
                <div class="yes-no-wrapper">
                    <a href="" data-induction="yes" class="active">Yes</a>
                    <a href="" data-induction="no">No</a>
                </div>
            </div>
        </div>
    </div>

</div>

<div class="white">
    <div class="add-to-cart-title">
        <div class="circle-with-text small pull-left">
            4
        </div>
        <div class="text pull-left">
            <h3 class="title"><span class="inline">I have read and understood the</span> <span class="underline-text"><a href="">terms and conditions </a></span></h3>
                <div class="subtitle error">
                    <span><i class="fa fa-exclamation-triangle" aria-hidden="true"></i><?php echo __("These must be accepted by the user."); ?></span>
                </div>

        </div>
    </div>
</div>

<div class="arrow"><span><?php echo __('Thank You, Please proceed to payment'); ?></span></div>