<div id="units" class="wrapper-block simple-products">

    <?php echo $this->getChildHtml('product.info.simples.title',true); ?>

    <?php foreach ($this->getOptions() as $option):
        if (strtolower($option->getTitle()) != strtolower('Induction Day')):
            ?>
            <div class="one-column">
                <div class="column">
                    <h3 class="title"><?php echo $option->getTitle(); ?><span
                            class="subtitle"><?php echo __('Units essential to this qualification'); ?></span></h3>
                    <table class="table bundle-simples" data-options-id="<?php echo $option->getId(); ?>">
                        <?php
                        foreach ($option->getSelections() as $data) :
                            $data = $data->load($data->getId()); ?>
                            <tr data-option-id="<?php echo $data->getSelectionId(); ?>">
                                <td>
                                    <?php echo $data->getSku(); ?>
                                </td>
                                <td>
                                    <?php echo $data->getName(); ?>
                                </td>
                                <td>

                                </td>
                                <td>
                                    <a
                                       class="btn-blue-standard open-simple-product <?php echo ($block->getData('data_modal_child')) ? "modal-child" : ""; ?>"
                                       <?php echo ($block->getData('data_modal_parent')) ? "data-modal-parent='".$block->getData('data_modal_parent')."'" : ""; ?>
                                       <?php echo ($block->getData('data_modal_child')) ? "data-modal-child='".$block->getData('data_modal_child')."'" : ""; ?>
                                       data-simpleproduct="<?php echo $data->getId(); ?>" >
                                        <?php echo __('View Unit'); ?>
                                    </a>
                                </td>
                            </tr>
                            <tr class="separator"/>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
            <?php
        endif;
    endforeach; ?>
</div>



