<script>// <![CDATA[
    require([
        'jquery',
        'ajaxproduct'
    ], function ($,ajaxproduct) {
        ajaxproduct._create();
    });
    // ]]>
</script>



<div class="modal fade" id="simple-product-modal" tabindex="-1" role="dialog" aria-labelledby="simpleProductModal">
    <div class="modal-dialog modal-lg" role="document">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <div class="modal-content">

            <div class="modal-body page-main">

                <div class="columns two-columns2">
                    <div class="column main">
                        <div class="page-title-wrapper product">
                            <%= content.title %>
                        </div>
                        <div class="wp-content">
                            <%= content.main %>
                        </div>
                    </div>
                    <div class="sidebar sidebar-main">
                        <%= content.sidebar %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>