<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    case 'other':
    break;
}
?>

<?php if ($exist):?>

    <div class="block-title title">
        <strong id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></strong>
    </div>
    <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">
        <div class="products wrapper grid products-grid products-<?php /* @escapeNotVerified */ echo $type; ?>">
                <?php $iterator = 0; ?>
                <?php foreach ($items as $_item):
                    $iterator++;
                    switch ($iterator)  {
                        case 1:
                            $class = 'green';
                            break;
                        case 2:
                            $class = 'yellow';
                            break;
                        case 3:
                            $class = 'orange';
                            break;
                    }
                    ?>
                <div class="product product-<?php /* @escapeNotVerified */ echo $type; ?> <?php echo $class?>">
                    <?php
                    $specialprice = $_item->getSpecialPrice();
                    $price = $_item->getPrice();
                    ?>
                    <div class="ribbon ribbon-top-right">
                        <?php   if ($specialprice) :?>
                           <span>£<?php echo round($price-$specialprice); ?><?php echo __(' Discount'); ?></span>
                        <?php endif; ?>
                    </div>
                    <div class="col-xs-12 col-md-8">
                        <div class="inner">
                        <div class="product-title">
                            <span><?php echo __($_item->getName()); ?></span>
                            <div class="subtitle">
                                <?php if($level = $_item->getLevel()) : ?>
                                    <span class="level"><?php echo __('Level '.$level); ?></span>
                                <?php endif; ?>
                                <?php if($unitCount = $_item->getUnitCount()) : ?>
                                    <span class="level"><?php echo __($unitCount.' Units'); ?></span>
                                <?php endif; ?>
                            </div>
                        </div>
                            <div class="content">

                                <?php $post = $this->getPostById($_item->load($_item->getId())->getData('associated_page'));
                                   echo  $post->getExcerpt();
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-4">
                        <div class="inner">
                         <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
                            <div class="actions">
                                <?php

                                ?>
                                    <a class="action tocart primary btn-blue-standard"
                                       href="<?php echo $_item->getProductUrl(); ?>"
                                       title="<?php /* @escapeNotVerified */ echo __('View') ?>">
                                        <span><?php /* @escapeNotVerified */ echo __('View') ?></span>
                                    </a>
                                    <form data-role="tocart-form" action="<?php echo $this->getAddToCartUrl($_item); ?>" method="post" class="add-to-cart-related">
                                    <?php echo $block->getBlockHtml('formkey')?>
                                        <button class="action tocart primary btn-blue-standard"
                                                data-post='<?php /* @escapeNotVerified */ echo $block->getPostData($_item); ?>'
                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart1') ?>">
                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                        </button>
                                    </form>
                            </div>
                        </div>
                    </div>
                </div>
                <?php endforeach ?>
        </div>
    </div>
<?php endif;?>
