<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = false;
            $showCart = true;
            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    case 'other':
    break;
}
?>

<?php if ($exist):?>

    <div class="block-title title">
        <strong id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></strong>
    </div>
    <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">
        <div class="products wrapper grid products-grid products-<?php /* @escapeNotVerified */ echo $type; ?>">
                <?php $iterator = 0; ?>
                <?php foreach ($items as $_item):
                    $iterator++;
                    switch ($iterator)  {
                        case 1:
                            $class = 'green';
                            break;
                        case 2:
                            $class = 'yellow';
                            break;
                        case 3:
                            $class = 'orange';
                            $iterator = 0;
                            break;
                    }
                    ?>
                <div class="product product-<?php /* @escapeNotVerified */ echo $type; ?> <?php echo $class?>">

                    <div class="col-xs-12 col-md-8">
                        <div class="inner">
                        <div class="product-title">
                            <span><?php echo __($_item->getName()); ?></span>
                            <div class="subtitle">
                                <?php if($level = $_item->getLevel()) : ?>
                                    <span class="level"><?php echo __('Level '.$level); ?></span>
                                <?php endif; ?>
                                <?php if($unitCount = $_item->getUnitCount()) : ?>
                                    <span class="level"><?php echo __($unitCount.' Units'); ?></span>
                                <?php endif; ?>
                            </div>
                        </div>
                            <div class="content">

                                <?php $post = $this->getPostById($_item->load($_item->getId())->getData('associated_page'));
                                   echo  $post->getExcerpt();
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-4">
                        <?php
                        $price = $_item->getFinalPrice();
                        $simlePrice = 0;
                        $simples = $_item->getTypeInstance(true)->getSelectionsCollection($_item->getTypeInstance(true)->getOptionsIds($_item), $_item);
                        foreach($simples as $simple)
                        {
                            $simlePrice += $simple->getFinalPrice();
                        }
                        ?>
                        <?php if($_item->getTypeId() == 'bundle') : ?>
                            <div class="ribbon ribbon-top-right">
                                <?php   if ($simlePrice > $price) :?>
                                    <span>£<?php echo round($simlePrice-$price); ?></span>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                        <div class="inner">
                            <?php if($_item->getFinalPrice() > 0) : ?>
                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
                            <?php endif; ?>
                            <div class="actions actions-primary">
                                   <a class="action tocart primary btn-blue-standard"
                                       href="<?php echo $_item->getProductUrl(); ?>"
                                       title="<?php /* @escapeNotVerified */ echo __('View') ?>">
                                        <span><?php /* @escapeNotVerified */ echo __('View') ?></span>
                                    </a>
                                <?php if($_item->getFinalPrice() > 0) : ?>
                                    <?php if ($showAddTo || $showCart): ?>
                                        <?php if ($showCart): ?>
                                            <div class="add-to-cart-related">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                        <button class="action tocart primary btn-blue-standard" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                        <button class="action tocart primary btn-blue-standard"
                                                                data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>

                                                        <div class="stock available btn-blue-standard"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="ribbon ribbon-top-right unavailable">
                                                            <span class="">Unavailable</span>
                                                        </div>
                                                        <div class="stock unavailable btn-blue-standard" data-product-id="<?php echo $_item->getEntityId();?>"><span><?php /* @escapeNotVerified */ echo __('Notify') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
                <?php endforeach ?>
        </div>
    </div>
    <?php $buttonTitle = __('Notify'); ?>
    <div class="" id="outofstock-modal-related">
        <div class="modal-body">
            <div class="modal-inner-shadow">
                <h3 class="text text-center"><?php echo __('Notify Your Interest'); ?></h3>
                <div class="content">
                    <form action="<?php /* @escapeNotVerified */ echo $block->getUrl('outofstock/index/notify') ?>"
                          method="post"
                          class="form notify"
                          id="form-validate"
                          data-mage-init='{"validation":{}}'
                          enctype="multipart/form-data">

                        <fieldset class="fieldset" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                            <input type="hidden" name="product" id="product-id" value="" />
                            <?php echo $block->getBlockHtml('formkey')?>
                            <div class="field note"><p>Please enter your email address below, you will recieve an email when this <?php echo __('course'); ?> become available.</p></div>
                            <div class="form-group email required">
                                <label for="email" class="label"><span><?php echo __('email'); ?></span></label>
                                <div class="control">
                                    <input type="email" name="email" alt="email" id="email_address" class="form-control input-text" data-validate="{required:true, 'validate-email':true}" />
                                </div>
                            </div>

                            <div class="actions-toolbar">
                                <div class="primary">
                                    <button type="submit"
                                            title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                                            class="action submit primary">
                                        <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                                    </button>
                                </div>
                            </div>
                        </fieldset>
                        </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        require(
            [
                'jquery',
                'Magento_Ui/js/modal/modal'
            ],
            function ($, modal) {
                var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    modalClass: 'modal-dialog',
                    title: '',
                    buttons: []
                };

                var popup = modal(options, $('#outofstock-modal-related'));
                $('.products-grid .stock.unavailable').on('click', function(e)
                {
                    $('#product-id').attr('value', $(this).attr('data-product-id'));
                    $('#outofstock-modal-related').modal('openModal');
                    e.preventDefault();
                });
            }
        );
    </script>
<?php endif;?>
