<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related courses and qualifications');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related courses and qualifications');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = false;
            $showCart = true;
            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other courses and qualifications you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other courses and qualifications you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New courses and qualifications');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    case 'other':
    break;
}
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();


?>
this is a test
<?php if ($exist):?>

    <div class="block-title title">
        <strong id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></strong>
    </div>
    <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">
        <div class="products wrapper grid products-grid products-<?php /* @escapeNotVerified */ echo $type; ?>">
                <?php $iterator = 0; ?>
                <?php foreach ($items as $_item):
                    $iterator++;
                    switch ($iterator)  {
                        case 1:
                            $class = 'green';
                            break;
                        case 2:
                            $class = 'yellow';
                            break;
                        case 3:
                            $class = 'orange';
                            $iterator = 0;
                            break;
                    }

                    ?>
                <div class="product product-<?php /* @escapeNotVerified */ echo $type; ?> <?php echo $class?>">

                    <div class="col-xs-12 col-md-8">
                        <div class="inner">
                        <div class="product-title">
                            <span><?php echo __($_item->getName()); ?></span>
                            <!--<div class="subtitle">
                                <?php if($level = $_item->getAttributeText('level')) : ?>
                                    <span class="level"><?php echo __('Level '.$level); ?></span>
                                <?php endif; ?>
                            </div>-->
                        </div>
                            <div class="content">

                                <?php $post = $this->getPostById($_item->load($_item->getId())->getData('associated_page'));
                                   echo  $post->getExcerpt();
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-4">
                        <?php
                        if($_item->getTypeId() == 'bundle') :
                            $price = $_item->getFinalPrice();
                            $simlePrice = 0;
                            $simples = $_item->getTypeInstance(true)->getSelectionsCollection($_item->getTypeInstance(true)->getOptionsIds($_item), $_item);
                            foreach($simples as $simple)
                            {
                                $simlePrice += $simple->getFinalPrice();
                            }
                            ?>

                            <div class="ribbon ribbon-top-right">
                                <?php   if ($simlePrice > $price) :?>
                                    <span>£<?php echo ceil($simlePrice-$price); ?></span>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                        <div class="inner">
                            <?php if($_item->getFinalPrice() > 0) : ?>
                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
                            <?php endif; ?>
                            <div class="actions actions-primary">
                                   <a class="action tocart primary btn-blue-standard"
                                       href="<?php echo $_item->getProductUrl(); ?>"
                                       title="<?php /* @escapeNotVerified */ echo __('View') ?>">
                                        <span><?php /* @escapeNotVerified */ echo __('View') ?></span>
                                    </a>
                                <?php if($_item->getFinalPrice() > 0) : ?>
                                    <?php if ($showAddTo || $showCart): ?>
                                        <?php if ($showCart): ?>
                                            <div class="add-to-cart-related">
                                                <?php
                                                $stockItem = $objectManager->get('\Magento\CatalogInventory\Api\StockRegistryInterface')->getStockItem($_item->getEntityId());
                                                if ($_item->isSaleable() && $stockItem->getData('is_in_stock')): ?>
                                                    <?php
                                                    $listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');
                                                    if(filter_var($_item->getData('has_options'))){
                                                        $query = ['startcustomization' => '1'];
                                                        $addToCartUrl = $_item->getUrlModel()->getUrl($_item).'?startcustomization=1';
                                                    }else{
                                                        $addToCartUrl = $listBlock->getAddToCartUrl($_item);
                                                    }
                                                    ?>
                                                    <form data-role="tocart-form" data-product-id="<?php echo $_item->getId();?>" action="<?php echo $addToCartUrl; ?>" method="post">
                                                        <?php echo $block->getBlockHtml('formkey')?>
	                                                    <?php $simpleVirtual = ($_item->getTypeId() === 'simple' || $_item->getTypeId() === 'virtual') ? true : false; var_dump($simpleVirtual); ?>
                                                        <button type="submit"
                                                                title="<?php /* @escapeNotVerified */ echo __('Add to Basket') ?>"
                                                                class="action tocart primary btn-blue-standard  <?php echo (!filter_var($_item->getData('has_options'), FILTER_VALIDATE_BOOLEAN)) ? 'simple-addtocart' : 'bundle-addtocart'; ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Basket') ?></span>
                                                        </button>
                                                    </form>
                                                <?php else: ?>
                                                    <?php
                                                    if ($stockItem->getData('is_in_stock')): ?>

                                                        <div class="stock available btn-blue-standard"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="ribbon ribbon-top-right unavailable">
                                                            <span class="">Unavailable</span>
                                                        </div>
                                                        <div class="stock unavailable btn-blue-standard" data-product-id="<?php echo $_item->getEntityId();?>"><span><?php /* @escapeNotVerified */ echo __('Notify') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>


                                            </div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                            <div class="hidden-terms hidden">
		                        <?php
			                        $contentBefore =  $post->getMetaValue('product_blocks_before_units');
			                        $contentAfter  =  $post->getMetaValue('product_blocks_after_units');

			                        $terms = "";

			                        if($contentBefore != null) {
				                        foreach ($contentBefore as $row) {
					                        foreach ($row as $field) {
						                        if ($field instanceof WP_Post) {
							                        $newPost = $this->getPostById($field->ID);
							                        if(stripos(strtolower($newPost->getPostTitle()), 'terms and conditions') !== false) {
								                        $terms .= $newPost->getMainContent();
							                        }
						                        }
					                        }
				                        }
			                        }

			                        if($contentAfter != null) {
				                        foreach ($contentAfter as $row) {
					                        foreach ($row as $field) {
						                        $newPost = $this->getPostById($field->ID);
						                        if(stripos(strtolower($newPost->getPostTitle()), 'terms and conditions') !== false) {
							                        $terms .= $newPost->getMainContent();
						                        }
					                        }
				                        }
			                        }

			                        echo $post->clean($terms);
		                        ?>
                            </div>
                        </div>
                    </div>
                </div>
                <?php endforeach ?>
        </div>
    </div>
	<?php echo $block->getChildHtml('');?>
<?php endif;?>
